import { Col, Row, Typography } from 'antd'
import Card from 'components/Card'
import TestimonialsCarousel from 'components/TestimonialsCarousel'
import VideoCard from 'components/VideoCard'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Careers.module.css'

const { Title, Text } = Typography

const Careers: NextPage = () => {
	return (
		<div>
			<Head>
				<title>leap.club | more women in leadership positions</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<Row className={styles.titleWrapper}>
				<Col xs={24}>
					<Title id={styles.titleText}>
						let&apos;s build a company together - join our all star founding
						team
					</Title>
				</Col>
			</Row>
			<Row
				justify='space-between'
				align='middle'
				className={styles.companyPitch}
			>
				<Col xs={24} md={10}>
					<div style={{ display: 'flex', flexDirection: 'column' }}>
						<Text id={styles.companyPitchText} style={{ marginBottom: '2rem' }}>
							we are building a community-led professional network for women
							with a simple mission - more women in leadership positions. we
							launched in may 2020, have early product-market fit and strong
							business signals. we are backed by some of the best investors in
							india.
						</Text>
						<Text id={styles.companyPitchText}>
							click{' '}
							<a
								href='https://love.leap.club'
								target='_blank'
								rel='noreferrer noopener'
							>
								here
							</a>{' '}
							to read what our members say about us ❤️
						</Text>
					</div>
				</Col>
				<Col xs={24} md={10}>
					<TestimonialsCarousel />
				</Col>
			</Row>

			<div className={styles.teamMembersWrapper}>
				<Row>
					<Col xs={24}>
						<Title id={styles.foundingMembersSectionHeading}>
							our founding team members have previously built companies like
							zomato, uber, linkedin, byju&apos;s, facebook
						</Title>
					</Col>
				</Row>

				<Row>
					<Col xs={24}></Col>
				</Row>
			</div>

			{/* Team Members Videos Section */}
			<div className={styles.teamMembersVideosWrapper}>
				<Row justify='center'>
					<Col xs={24}>
						<Title id={styles.foundingMembersSectionHeading}>
							👀 here are some videos that will tell you more about our team and
							their experience of building leap.club
						</Title>
					</Col>
				</Row>

				<Row
					justify='space-between'
					style={{ backgroundColor: '#e5e5e5', padding: '0.5rem' }}
				>
					<Col xs={24} md={6}>
						<VideoCard
							link='https://youtube.com/embed/SihSIlXQFm4'
							text='‘meet our first team member’'
						/>
					</Col>
					<Col xs={24} md={6}>
						<VideoCard
							link='https://youtube.com/embed/FdJmM2AaZmA'
							text='‘building leap with an incredible team’'
						/>
					</Col>
					<Col xs={24} md={6}>
						<VideoCard
							link='https://youtube.com/embed/QG9DWbylotE'
							text='‘becoming a founding team member’'
						/>
					</Col>
					<Col xs={24} md={6}>
						<VideoCard
							link='https://youtube.com/embed/5ECw8jpAC1o'
							text="‘shit we've heard while building leap.club’"
						/>
					</Col>
				</Row>
			</div>

			{/* Values and guiding principles section */}
			<div className={styles.teamMembersVideosWrapper}>
				<Row justify='center'>
					<Col xs={24}>
						<Title
							id={styles.foundingMembersSectionHeading}
							style={{ textAlign: 'center' }}
						>
							📝 our values and guiding principles
						</Title>
					</Col>
				</Row>
				<Row justify='space-between'>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/think.svg'
							heading='first principle thinking'
							description='when in doubt, ask yourself, will this help our mission? if yes, do it'
						/>
					</Col>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/process.svg'
							heading='process ≠ progress'
							description='innovation is our best friend and getting attached to a process, our worst enemy. everything can be improved'
						/>
					</Col>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/80-20.svg'
							heading='80/20'
							description="feedback moves things forward and helps you grow. don't get offended or take it personally. when giving feedback, focus on the 'delta'. the 20% that can change the 80%"
						/>
					</Col>
				</Row>
				<Row justify='space-between' style={{ marginTop: '2rem' }}>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/dream-big.svg'
							heading='dream big'
							description='we believe we are building a multi unicorn. remember, nothing big ever comes easy. work hard. enjoy the ride'
						/>
					</Col>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/right.svg'
							heading='right > fast'
							description='play the long game'
						/>
					</Col>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/priority.svg'
							heading='prioritize ruthlessly'
							description='focus on needle movers only'
						/>
					</Col>
				</Row>
			</div>

			{/* Perks Section */}
			<div className={styles.perksSectionWrapper}>
				<Row justify='center'>
					<Col xs={24}>
						<Title
							id={styles.foundingMembersSectionHeading}
							style={{ textAlign: 'center' }}
						>
							🎉 perks of working at leap.club
						</Title>
					</Col>
				</Row>
				<Row justify='space-between'>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/think.svg'
							heading='flexible leave policy'
							description='vacation leaves, wellness leaves, compulsory down time.we trust you to do the right thing'
						/>
					</Col>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/process.svg'
							heading='5 day work week'
							description='we try to combine speed with enough downtime. burnouts are real'
						/>
					</Col>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/80-20.svg'
							heading="esop's & regular appraisals"
							description="let's win together"
						/>
					</Col>
				</Row>
				<Row justify='space-between' style={{ marginTop: '2rem' }}>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/dream-big.svg'
							heading='remote work'
							description='gurgaon is our hq but you decide where you want to work from'
						/>
					</Col>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/right.svg'
							heading='dreamers'
							description='you work with folks who dream big and want to build a multi unicorn'
						/>
					</Col>
					<Col xs={24} md={7}>
						<Card
							icon='/assets/icons/priority.svg'
							heading='diversity goals'
							description='72% of the team is women'
						/>
					</Col>
				</Row>
			</div>
		</div>
	)
}

export default Careers
