import type { NextPage } from "next";
import Head from "next/head";
import Layout from "components/Layout";
import { Scrollbars } from "react-custom-scrollbars-2";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>leap.club | more women in leadership positions</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Scrollbars universal autoHide style={{ height: "100vh" }}>
        <Layout>
          <div style={{ minHeight: "150vh" }}>
            <h4>asdfasdf</h4>
          </div>
        </Layout>
      </Scrollbars>
    </div>
  );
};

export default Home;
