import { Col, Row } from 'antd'
import AdVideos from 'components/AdVideos'
import EndSection from 'components/EndSection'
import Jumbotron from 'components/Jumbotron'
import MembersCompanies from 'components/MembersCompanies'
import SneakPeak from 'components/SneakPeak'
import Testimonials from 'components/Testimonials'
import Waitlist from 'components/Waitlist'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>leap.club | more women in leadership positions</title>
				<meta name='description' content='Generated by create next app' />
			</Head>

			<Row className={styles.mainSectionWrapper}>
				<Col xs={24} md={12} xxl={9}>
					<Jumbotron />
				</Col>
				<Col xs={24} md={11}>
					<Waitlist />
				</Col>
			</Row>
			<Row className={styles.membersCompaniesWrapper}>
				<Col span={24}>
					<MembersCompanies />
				</Col>
			</Row>
			<Row className={styles.testimonialsContainer}>
				<Col span={24}>
					<Testimonials />
				</Col>
			</Row>
			<Row className={styles.sneakPeakWrapper}>
				<Col span={24}>
					<SneakPeak />
				</Col>
			</Row>
			<Row className={styles.adVideosContainer}>
				<Col span={24}>
					<AdVideos />
				</Col>
			</Row>
			<Row className={styles.endSectionContainer}>
				<Col span={24}>
					<EndSection />
				</Col>
			</Row>
		</div>
	)
}

export default Home
